### ISSUE TITLE
[Question] Is this this plugin usable with ionic (typescript) ?

### ISSUE THREAD

**Issue by thiphariel** [stalniy/cordova-plugin-googlemaps#13]
Hi.

As a fork of cordova-plugin-googlemaps, is this plugin usable with the @ionic-native (https://ionicframework.com/docs/native/google-maps/) typescript interface ?

Thanks

**Comment by stalniy** [comment]
Frankly speaking, I don't know :) Currently I use this fork in my application. In the last few months didn't have time to workr on it but believe that will proceed in a month or so.

The most important part of this fork was merged in original cordova-plugin-googlemaps package (it was a complete rewrite of `BaseClass`). So, currently the only difference between that 2 is:
* support for enabling my location pointer without showing native "mylocation" button (the change was declined by owner https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1612)
* additional unit tests for `BaseClass`
